# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Yuanxun Zhang
tagline:          'A Jekyll theme'
description:      'PhD candidate in computer science <a href="https://missouri.edu/" target="_blank">@Mizzou</a>'
url:              http://hyde.getpoole.com
baseurl:          '/me/'

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/zhangyuanxun/me

# Social usernames/URLs
linkedin_link: https://www.linkedin.com/in/yuanxun-zhang-79334b87/
